# Build Windows service
# versione 1.1.0
# Compila soluzione e la pubblica nella windows dir

steps:
- checkout: self
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: MSBuild@1
  displayName: 'Compilazione Web API LibraryManager'
  inputs:
      solution: '**/LibraryManager.csproj'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: ' /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=$(build.artifactStagingDirectory)/publish/LibMan'
- task: MSBuild@1
  displayName: 'Compilazione Web App BooksBay'
  inputs:
      solution: '**/BooksBay.csproj'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: ' /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=$(build.artifactStagingDirectory)/publish/BooksBay'

        
- publish: $(build.artifactstagingdirectory)/publish/LibMan
  displayName: 'Pubblicazione artefatto LibraryManager'
  artifact: WebAPI

- publish: $(build.artifactstagingdirectory)/publish/BooksBay
  displayName: 'Pubblicazione artefatto BooksBay'
  artifact: WebApp